/*export const SET_RELEASE_REQUESTS = "SET_RELEASE_REQUESTS";
export const SET_RELEASE_REQUESTS_FAILED = "SET_RELEASE_REQUESTS_FAILED";
export const SET_PAGINATION_DATA = "SET_PAGINATION_DATA";
export const SET_NEW_PAGE = "SET_NEW_PAGE";
export const SET_SELECT_ALL = "SET_SELECT_ALL";*/

export const SET_RELEASE_REQUESTS_PARAMS = "SET_RELEASE_REQUESTS_PARAMS";
export const INIT_RELEASE_REQUESTS = "INIT_RELEASE_REQUESTS";
export const SET_LOADING_STATUS = "SET_LOADING_STATUS";
export const SET_CHECKED_REQUESTS = "SET_CHECKED_REQUESTS";
